fixtures:
  repositories:
    stdlib: http://github.com/puppetlabs/puppetlabs-stdlib.git
    inifile: http://github.com/puppetlabs/puppetlabs-inifile.git
    concat: http://github.com/puppetlabs/puppetlabs-concat.git
    puppetdbquery: http://github.com/dalen/puppet-puppetdbquery.git
    sshkeys: http://github.com/jtopjian/puppet-sshkeys.git
  symlinks:
    xldeploy: "#{source_dir}"

