rvm: 1.9.3
env:
- PUPPET_VERSION=3.6
- PUPPET_VERSION=3.5
- PUPPET_VERSION=3.4
notifications:
  hipchat:
    rooms:
      secure: OoKJMDdxaVJJBeLSyGN1Yf3ks189c5rZ2wj8OtlqkHtYlWDr8ViumJTMxWFNl5EUbx+BKCMArTsx9u4ahYvdJzaDLNaKD0l4hXQ6NdxrziI8y2boQdAeRXzPK02jRo3b3GG3Nmia7k5xkXF7Oztb5kT/q5hPM+Lbrq+CEGmi60U=
